steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/edgs || true']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/edgs', '--cache-from', 'gcr.io/$PROJECT_ID/edgs', '.']
images:
- 'gcr.io/$PROJECT_ID/edgs'